# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'
use_frameworks!
target 'genido' do
	project 'genido.xcodeproj'
	pod 'Firebase/Messaging', '9.3.0'
end
